name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        version: [stable]
        variant: 
          - examples/root-configs/esp32-test
          - examples/root-configs/hp-debug
          - examples/root-configs/hp-sejour
          - examples/m5stack-atoms3/atom-m5
          - examples/xiao-esp32s3/heatpump-xiaoESP32S3
          - examples/modular-hvac/hvac-sample
    container:
      image: ghcr.io/esphome/esphome:${{ matrix.version }}
    env:
      USERNAME: test
      PASSWORD: github-run
    steps:
    - uses: actions/checkout@v4
    - name: Generate random secret
      env:
        keys: >-
        keys: >-
          mqtt_password ota_pwd
          wifi_ssid wifi_password
          wifi_ssid2 wifi_password2
          wifi_ssid3 wifi_password3
          iot_ssid iot_password iot_domain fallback_password api_key
          broker m5_login m5_password
        enc_keys: encryption_key_sejour encryption_key
      run: |
        for key in $keys ; do
          value=`head -c 100 /dev/urandom | base64 | cut -c 1-24 | head -n1`
          echo "${key}: ${value}" >> secrets.yaml
        done
        for key in $enc_keys ; do
          value=`head -c 32 /dev/urandom | base64`
          echo "${key}: ${value}" >> secrets.yaml
        done
        # Copy secrets to example directories
        cp secrets.yaml examples/root-configs/
        cp secrets.yaml examples/m5stack-atoms3/
        cp secrets.yaml examples/m5stack-atoms3/includes/
        cp secrets.yaml examples/xiao-esp32s3/
        cp secrets.yaml examples/xiao-esp32s3/common/
        cp secrets.yaml examples/modular-hvac/
    - run: esphome compile ${{ matrix.variant }}.yaml
